### ISSUE TITLE
Simple things are complicated

### ISSUE THREAD

**Issue by lgengsy** [vuitv/flutter_clean_architecture#1]
Simple things are complicated，Do things that are not necessary

**Comment by lgengsy** [comment]
why not getX

**Comment by vuitv** [comment]
Thanks your feedback! i has read blog Should use GetX
https://medium.com/@darwinmorocho/flutter-should-i-use-getx-832e0f3a00e8

**Comment by sxywalkr** [comment]
will you use getx?

**Comment by vuitv** [comment]
> will you use getx?

I used getx for two small projects, and decided to use bloc for the big company project

**Comment by vuitv** [comment]
aaaâ
